### ISSUE TITLE
Create post with PDF in desktop

### ISSUE THREAD

**Issue by Luiz-FS** [eciis/web#1364]
Creating a post with pdf on the desktop screen is broken

![screenshot from 2018-12-17 15-22-26](https://user-images.githubusercontent.com/18005317/50107002-267d7800-0210-11e9-88cf-d6408d5b3144.png)

**Comment by JuliePessoa** [comment]
Left image is the right one.

![image](https://user-images.githubusercontent.com/7011394/52080147-dd8e4280-2575-11e9-913a-441a7db18ae9.png)
