### ISSUE TITLE
its not possible to visualize pdf in the application.

### ISSUE THREAD

**Issue by JuliePessoa** [eciis/web#1423]
**Describe the bug**
Pdf files are not being visualized. 

**To Reproduce**
1. Go to 'Portfolio' in a institution page
2. Or create a post with an pdf and try to visualize it.
3. See console error.

**Screenshots**
![image](https://user-images.githubusercontent.com/7011394/52415079-d78fe880-2ac4-11e9-9f02-44c72a0bd664.png)

**Comment by Luiz-FS** [comment]
Fixed. it was only necessary to create a cors.json file with the following settings and, in the terminal, execute the command gsutil cors set cors.json gs://development-cis.appspot.com
